### ISSUE TITLE
Display (settings)

### ISSUE THREAD

**Issue by ghost** [CaptainStouf/raspberry_lcd4x20_I2C#1]
Are there advanced options like:
- backround light on/off
- display on/off
  (- maybe even dim backround light?)
  possible?

**Comment by ArcadiaLabs** [comment]
No, these features are not present.
However, controlling backlight using a GPIO (or PWM for dimming) should be easy.

**Comment by mlechner** [comment]
@CaptainStouf 
Nothing happened here since almost 3 years. The question has been answered. How about clsoing this "issue"?
