### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by marksev1** [CaptainStouf/raspberry_lcd4x20_I2C#3]
If I understand correctly here each line in the display has to be separately filled with text. What about if I have a big amount of text, for example here: http://meteo.arso.gov.si/uploads/probase/www/fproduct/text/sl/fcast_si_text.html if I would want to print all the text under "Napoved za Slovenijo", how would I achieve that?  Since I already have a python script which prints all the text from there and I would really like to display it on 20x4 display. Probably all of it wouldn't fit so how would I do the scrolling?

Hopefully you can help me!
Thanks CaptainStouf!

**Comment by ArcadiaLabs** [comment]
Hi,
I didn't have the time to check this, sorry. Did you try using this trick ? -> http://www.root9.net/2012/10/raspberry-pi-lcd-scroller-tutorial.html

**Comment by marksev1** [comment]
Thanks for the link, I'll read it. Out of your head, would this work for a text source that doesn't have all the time the same amount of text. Like the weather forecast text I scrap from the html page of the weather forecast service. (currently I just print it into the terminal)

**Comment by ArcadiaLabs** [comment]
Yes, the snipplet linked above should work with text of any length.
Once I got the time, I may add this function to the lib.

**Comment by marksev1** [comment]
Cool, thanks!
